openapi: 3.0.3
info:
  title: AnimationKit API
  version: 0.1.0
servers:
  - url: https://api.animationkit.local
paths:
  /health:
    get:
      operationId: getHealth
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                required: [status]
  /animations:
    get:
      operationId: listAnimations
      summary: List animations
      parameters:
        - in: query
          name: pageToken
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: integer
            minimum: 1
            maximum: 200
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnimationListResponse'
    post:
      operationId: submitAnimation
      summary: Submit an animation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Animation'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                required: [id]
        '400':
          description: Invalid payload
  /animations/{id}:
    get:
      operationId: getAnimation
      summary: Fetch an animation by identifier
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnimationResource'
        '404':
          description: Not Found
    put:
      operationId: updateAnimation
      summary: Update an animation resource
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAnimationRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnimationResource'
        '400':
          description: Invalid payload
        '404':
          description: Not Found
  /evaluate:
    post:
      operationId: evaluateTimeline
      summary: Evaluate a timeline at time
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                timeline:
                  $ref: '#/components/schemas/Timeline'
                t:
                  type: number
              required: [timeline, t]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: number
                required: [value]
  /evaluate/bulk:
    post:
      operationId: evaluateTimelineBulk
      summary: Evaluate a timeline across multiple samples
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkEvaluationRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BulkEvaluationResponse'

components:
  schemas:
    Easing:
      type: string
      enum: [linear, easeIn, easeOut, easeInOut]
    Keyframe:
      type: object
      properties:
        time:
          type: number
        value:
          type: number
        easing:
          $ref: '#/components/schemas/Easing'
      required: [time, value]
    Timeline:
      type: object
      properties:
        keyframes:
          type: array
          items:
            $ref: '#/components/schemas/Keyframe'
      required: [keyframes]
    Position:
      type: object
      properties:
        x:
          $ref: '#/components/schemas/Timeline'
        y:
          $ref: '#/components/schemas/Timeline'
    Color:
      type: object
      properties:
        r:
          $ref: '#/components/schemas/Timeline'
        g:
          $ref: '#/components/schemas/Timeline'
        b:
          $ref: '#/components/schemas/Timeline'
        a:
          $ref: '#/components/schemas/Timeline'
    Animation:
      type: object
      properties:
        duration:
          type: number
        opacity:
          $ref: '#/components/schemas/Timeline'
        position:
          $ref: '#/components/schemas/Position'
        scale:
          $ref: '#/components/schemas/Timeline'
        rotation:
          $ref: '#/components/schemas/Timeline'
        color:
          $ref: '#/components/schemas/Color'
      required: [duration]
    AnimationSummary:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        duration:
          type: number
        updatedAt:
          type: string
          format: date-time
      required: [id, duration]
    AnimationResource:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        tags:
          type: array
          items:
            type: string
        animation:
          $ref: '#/components/schemas/Animation'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required: [id, animation]
    AnimationListResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/AnimationSummary'
        nextPageToken:
          type: string
      required: [items]
    UpdateAnimationRequest:
      type: object
      properties:
        animation:
          $ref: '#/components/schemas/Animation'
        name:
          type: string
        tags:
          type: array
          items:
            type: string
      required: [animation]
    BulkEvaluationRequest:
      type: object
      properties:
        timeline:
          $ref: '#/components/schemas/Timeline'
        samples:
          type: array
          items:
            type: number
      required: [timeline, samples]
    EvaluationSample:
      type: object
      properties:
        t:
          type: number
        value:
          type: number
      required: [t, value]
    BulkEvaluationResponse:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/EvaluationSample'
      required: [results]
