openapi: 3.0.3
info:
  title: AnimationKit API
  version: 0.1.0
servers:
  - url: https://api.animationkit.local
paths:
  /health:
    get:
      operationId: getHealth
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                required: [status]

