name: CI

on:
  push:
    branches: [ main, "feature/**" ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    name: Build and Test (macOS)
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Select Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'
      - name: Show toolchain
        run: swift --version
      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: |
            ~/.swiftpm
          key: macos-spm-${{ hashFiles('**/Package.resolved') }}
      - name: Build
        run: swift build --disable-sandbox
      - name: Test
        run: swift test --disable-sandbox

  linux:
    name: Build and Test (Linux)
    runs-on: ubuntu-22.04
    container:
      image: swift:6.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Show toolchain
        run: swift --version
      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: |
            /github/home/.swiftpm
          key: linux-spm-${{ hashFiles('**/Package.resolved') }}
      - name: Build
        run: swift build --disable-sandbox
      - name: Test
        run: swift test --disable-sandbox
